name: balo
description: A source control in the style of git
version: 1.0.0
repository: https://github.com/bruc3balo/Source-Control

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  freezed: ^2.5.7
  dart_levenshtein: ^1.0.1
  args: ^2.6.0
  crypto: ^3.0.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

executables:
  balo: balo