name: Dart CI with Merge to Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up the Dart SDK
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      # Install dependencies
      - name: Install dependencies
        run: dart pub get

      # Run Dart tests
      - name: Run tests
        run: dart run test --concurrency=1
